import type { Confidence, FactState, Localized, SourceKind } from "./types";

export const STATE_LABEL: Record<FactState, Localized> = {
  confirmed: { en: "Confirmed", zh: "已确认" },
  proposed: { en: "Proposed", zh: "待确认" },
  inferred: { en: "Inferred", zh: "推断" },
  recheck: { en: "Recheck", zh: "需复核" },
};

export const CONFIDENCE_LABEL: Record<Confidence, Localized> = {
  high: { en: "High confidence", zh: "置信度高" },
  medium: { en: "Medium confidence", zh: "置信度中" },
  recheck: { en: "Needs recheck", zh: "需复核" },
};

export const SOURCE_LABEL: Record<SourceKind, Localized> = {
  official: { en: "Official", zh: "官方" },
  platform: { en: "Platform", zh: "平台" },
  user: { en: "Your upload", zh: "你上传" },
};

export const DEMO_UI = {
  fixture: { en: "Demo fixture · not live data", zh: "Demo fixture · 非实时数据" },
  fixtureLong: {
    en: "Every conversation, price, review and account in this demo is a fixed sample. Nothing here reads live inventory or places a real order.",
    zh: "这个 Demo 里的所有对话、价格、评论和账户都是固定示例。不读取任何实时库存，也不会下真实订单。",
  },
  localTime: { en: "Demo time 14:20", zh: "Demo 时间 14:20" },

  ability: {
    ask: { en: "Ask the vague thing clearly, then turn it into a plan.", zh: "把模糊的想法问清楚，再落成行程。" },
    canvas: { en: "Every change is explained first, then waits for your confirmation.", zh: "行程的每一次变化都先解释，再由你确认。" },
    copilot: { en: "Remember your pace, budget and allergies, so you do not repeat yourself.", zh: "记住你的节奏、预算和忌口，下一次不用重讲。" },
    explore: { en: "See the place clearly before you commit to it.", zh: "先看清楚一个地方，再决定要不要去。" },
    tools: { en: "The errands a trip needs, without leaving the trip.", zh: "行程里要办的杂事，不用离开行程去办。" },
    today: { en: "What to do right now, and what to do if it breaks.", zh: "此刻该做什么，出问题时又该做什么。" },
  } satisfies Record<string, Localized>,

  shell: {
    fullscreen: { en: "Full screen", zh: "全屏" },
    exitFullscreen: { en: "Exit full screen", zh: "退出全屏" },
    escHint: { en: "Esc to exit", zh: "按 Esc 退出" },
    openDemo: { en: "Open the demo", zh: "打开 Demo" },
    mobileNav: { en: "Demo navigation", zh: "Demo 导航" },
  } satisfies Record<string, Localized>,

  status: {
    trip: { en: "Trip", zh: "行程" },
    context: { en: "Context", zh: "当前" },
    states: { en: "States", zh: "状态" },
  } satisfies Record<string, Localized>,

  tour: {
    title: { en: "Take the tour", zh: "跟着走一遍" },
    steps: [
      { en: "Ask · build a Canvas", zh: "Ask · 生成 Canvas" },
      { en: "Canvas · confirm a diff", zh: "Canvas · 确认改动" },
      { en: "Copilot · long-term memory", zh: "Copilot · 长期记忆" },
      { en: "Ask · check an imported guide", zh: "Ask · 检查导入的攻略" },
    ],
  },

  canvas: {
    timeline: { en: "Timeline", zh: "时间线" },
    map: { en: "Map", zh: "地图" },
    bookings: { en: "Bookings", zh: "预订" },
    version: { en: "Version", zh: "版本" },
    restore: { en: "Restore this version", zh: "回到这个版本" },
    diffOpen: { en: "Review changes", zh: "查看改动" },
    diffClose: { en: "Close", zh: "关闭" },
    acceptAll: { en: "Accept all", zh: "全部接受" },
    accept: { en: "Accept", zh: "接受" },
    reject: { en: "Reject", zh: "拒绝" },
    rework: { en: "Ask for another option", zh: "换个方案" },
    accepted: { en: "Accepted", zh: "已接受" },
    rejected: { en: "Rejected", zh: "已拒绝" },
    reason: { en: "Why", zh: "原因" },
    trigger: { en: "Triggered by", zh: "触发来源" },
    applied: { en: "Applied to the Canvas", zh: "已应用到 Canvas" },
    rejectedNote: { en: "Rejected. Copilot recorded this as negative feedback.", zh: "已拒绝。Copilot 已把它记为一次负反馈。" },
    nothingApplied: { en: "Nothing has changed on your Canvas yet.", zh: "你的 Canvas 目前还没有任何变化。" },
    duration: { en: "Duration", zh: "时长" },
    transfer: { en: "Getting there", zh: "交通" },
    cost: { en: "Cost", zh: "费用" },
    risk: { en: "Watch out", zh: "注意" },
    evidence: { en: "Source", zh: "来源" },
    stay: { en: "Overnight", zh: "住宿" },
    compare: { en: "Compare", zh: "对比" },
    mapCaption: { en: "Stops in order, with the moves between them", zh: "按顺序排列的节点与移动" },
    generating: { en: "Generating Trip Canvas", zh: "正在生成 Trip Canvas" },
    emptyTitle: { en: "No trip yet", zh: "还没有行程" },
    uploadTypes: { en: "PDF · image · link · plain text — nothing is uploaded in this demo", zh: "PDF · 图片 · 链接 · 纯文本——Demo 不会真的上传" },
  } satisfies Record<string, Localized>,

  chat: {
    you: { en: "You", zh: "你" },
    composer: { en: "Continue with your preferences…", zh: "继续描述你的需求…" },
    send: { en: "Message sent", zh: "消息已发送" },
    pick: { en: "Pick one, or type your own", zh: "选一个，或者自己输入" },
    cannotConfirm: { en: "I can't confirm this", zh: "这一条我无法确认" },
    officialChannel: { en: "Official channel", zh: "官方渠道" },
    nextStep: { en: "What you can do", zh: "你可以这样做" },
    viewMemory: { en: "View in Copilot", zh: "在 Copilot 中查看" },
    copy: { en: "Copy", zh: "复制" },
    toCanvas: { en: "Add to Canvas", zh: "加入 Canvas" },
    another: { en: "Another option", zh: "换个方案" },
    wrong: { en: "This looks wrong", zh: "这条不对" },
    copied: { en: "Copied to clipboard (demo state only)", zh: "已复制（仅为 Demo 状态）" },
    wrongNote: { en: "Marked as wrong. Copilot recorded it and will avoid this pattern.", zh: "已标为不对。Copilot 记下了，之后会避开这个模式。" },
    anotherNote: { en: "Loaded the second preset answer for this turn.", zh: "已切换到这一轮的第二个预置回答。" },
  } satisfies Record<string, Localized>,

  copilot: {
    memory: { en: "Memory", zh: "记忆" },
    tools: { en: "Tools", zh: "工具" },
    memoryTitle: { en: "A trip profile that learns over time", zh: "越聊越懂你的旅行方式" },
    toolsTitle: { en: "The errands a trip actually needs", zh: "行程里真正要办的杂事" },
    source: { en: "Source", zh: "来源" },
    updated: { en: "Updated", zh: "更新" },
    impact: { en: "Already changed", zh: "已经改变了" },
    hard: { en: "Hard constraint · cannot be overridden automatically", zh: "硬约束 · 不可被自动推翻" },
    confirm: { en: "Confirm", zh: "确认" },
    forget: { en: "Forget", zh: "忘记" },
    forgotten: { en: "Forgotten. Future suggestions will not use it.", zh: "已忘记，未来建议不会再使用。" },
    pause: { en: "Pause long-term memory", zh: "暂停长期记忆" },
    resume: { en: "Resume long-term memory", zh: "恢复长期记忆" },
    paused: { en: "Long-term memory is paused. Ask will stop quoting your profile.", zh: "长期记忆已暂停，Ask 将不再引用你的画像。" },
    exportTitle: { en: "Export my profile", zh: "导出我的画像" },
    exportBody: { en: "A static preview of what you would take with you.", zh: "你可以带走的内容的静态预览。" },
    preview: { en: "Before and after", zh: "改动前后" },
    before: { en: "Before", zh: "改动前" },
    after: { en: "After", zh: "改动后" },
    openCanvas: { en: "View in Canvas", zh: "在 Canvas 中查看" },
    boundary: { en: "What this tool does not claim", zh: "这个工具不声明什么" },
  } satisfies Record<string, Localized>,

  explore: {
    title: { en: "Places, seen clearly", zh: "把地方看清楚" },
    filters: { en: "Filters", zh: "筛选" },
    anyPrice: { en: "Any price", zh: "不限价位" },
    intlCard: { en: "Takes international cards", zh: "接受境外卡" },
    englishService: { en: "English service", zh: "英文服务" },
    area: { en: "Area", zh: "区域" },
    anyArea: { en: "Any area", zh: "不限区域" },
    reset: { en: "Reset", zh: "重置" },
    results: { en: "results", zh: "个结果" },
    noResults: { en: "No place matches all of these filters", zh: "没有同时满足这些筛选的地点" },
    noResultsBody: { en: "Loosen one filter, or ask VisePanda to look wider.", zh: "放宽一个条件，或让 VisePanda 扩大范围。" },
    payment: { en: "Payment", zh: "支付" },
    language: { en: "Language & service", zh: "语言与服务" },
    entry: { en: "Entry & booking", zh: "入场与预约" },
    sourceLine: { en: "Source and recheck", zh: "来源与复核" },
    ask: { en: "Ask VisePanda about this", zh: "就这个地点提问" },
    add: { en: "Add to Trip Canvas", zh: "加入 Trip Canvas" },
    added: { en: "Added to Trip Canvas as a proposal", zh: "已作为提案加入 Trip Canvas" },
    citySoonTitle: { en: "This city is being prepared", zh: "这个城市正在整理" },
    citySoonBody: { en: "Shanghai has the complete category, filter and POI flow today.", zh: "目前上海已开放完整的分类、筛选和 POI 详情。" },
    poiCount: { en: "places", zh: "个地点" },
    ready: { en: "Ready", zh: "已开放" },
    preparing: { en: "In preparation", zh: "整理中" },
  } satisfies Record<string, Localized>,

  today: {
    title: { en: "Today", zh: "今天" },
    next: { en: "Next", zh: "下一步" },
    conditions: { en: "Right now", zh: "当前条件" },
    recovery: { en: "If it goes wrong", zh: "出问题时" },
    bring: { en: "Bring", zh: "随身携带" },
    leaveAt: { en: "Leave at", zh: "出发时间" },
    seeChange: { en: "See the change", zh: "查看改动" },
  } satisfies Record<string, Localized>,

  sim: {
    title: { en: "Trip simulator", zh: "行程模拟器" },
    run: { en: "Run the checks", zh: "运行检查" },
    running: { en: "Checking…", zh: "检查中…" },
    pass: { en: "Pass", zh: "通过" },
    warn: { en: "Watch", zh: "需注意" },
    fail: { en: "Not workable", zh: "不可行" },
    alternatives: { en: "Two alternatives", zh: "两个替代方案" },
    toDiff: { en: "Send to the diff", zh: "送入改动确认" },
    ignore: { en: "Ignore all", zh: "全部忽略" },
  } satisfies Record<string, Localized>,

  user: {
    account: { en: "Account", zh: "账户" },
    travelProfile: { en: "Travel Profile", zh: "旅行画像" },
    memory: { en: "VisePanda Memory", zh: "VisePanda 记忆" },
    preferences: { en: "Preferences", zh: "偏好" },
    privacy: { en: "Privacy & Data", zh: "隐私与数据" },
    edit: { en: "Edit profile", zh: "编辑画像" },
    cancel: { en: "Cancel", zh: "取消" },
    save: { en: "Save and preview impact", zh: "保存并预览影响" },
    saved: { en: "Profile updated. Future suggestions will use the new budget and walking intensity.", zh: "画像已更新，后续建议将使用新的预算与步行强度。" },
    affects: { en: "This change affects", zh: "本次改动会影响" },
    units: { en: "Units", zh: "单位" },
    temperature: { en: "Temperature", zh: "温度" },
    notifications: { en: "Notifications", zh: "通知" },
    defaultStart: { en: "Default start time", zh: "默认出发时间" },
    dataUse: { en: "How your data is used", zh: "数据用途" },
    dataUseItems: [
      { en: "Building and checking your itinerary", zh: "生成与检查你的行程" },
      { en: "Personalising suggestions", zh: "个性化建议" },
      { en: "Safety and abuse prevention", zh: "安全与滥用防护" },
    ],
    exportData: { en: "Export my data", zh: "导出我的数据" },
    deleteData: { en: "Delete my data", zh: "删除我的数据" },
    deleteWarn: { en: "Deletion removes your profile, memory and saved places. It cannot be undone.", zh: "删除会移除你的画像、记忆和收藏地点，且不可恢复。" },
    noCollection: { en: "This demo collects, transmits and stores no real user data.", zh: "本 Demo 不收集、不传输、不存储任何真实用户数据。" },
  },

  empty: {
    loading: { en: "Working…", zh: "处理中…" },
    partial: { en: "Partly parsed", zh: "部分解析成功" },
    retry: { en: "Fill it in by hand", zh: "手工补充" },
    offline: { en: "Offline · showing what works without a connection", zh: "离线 · 只展示无需联网的部分" },
    normal: { en: "Connected", zh: "已联网" },
    simulateOffline: { en: "Preview offline", zh: "预览离线状态" },
    simulatePartial: { en: "Preview partial failure", zh: "预览部分失败" },
    offlineBody: { en: "Saved cards and bilingual addresses remain available. Live rechecks, provider handoffs and new lookups wait for a connection.", zh: "已保存的卡片和双语地址仍可使用；实时复核、渠道跳转和新查询需等待网络恢复。" },
    partialBody: { en: "Four results are ready. One provider did not answer, so its field stays marked for recheck instead of being guessed.", zh: "4 条结果可用；1 个渠道没有响应，该字段保持需复核，不会被猜测填充。" },
  } satisfies Record<string, Localized>,
};
