// Regenerates lib/map-geometry.ts from Natural Earth 1:50m data (public domain).
//   node scripts/build-map.mjs <admin0.geojson> <admin1.geojson> [output]
// Country bounds come from the admin-0 selection only, so city projection stays
// stable when province geometry is added or refreshed.
import { readFile, writeFile } from "node:fs/promises";

const [
  admin0Input = "/tmp/ne_50m_admin_0_countries.geojson",
  admin1Input = "/tmp/ne_50m_admin_1_states_provinces.geojson",
  output = "lib/map-geometry.ts",
] = process.argv.slice(2);

const countries = new Set(["CHN", "TWN", "HKG", "MAC"]);
const viewBox = { width: 1000, height: 700, padding: 18 };
const EPSILON = 0.35; // simplification tolerance in projected units

const admin0 = JSON.parse(await readFile(admin0Input, "utf8"));
const admin1 = JSON.parse(await readFile(admin1Input, "utf8"));
const selected = admin0.features.filter((feature) => countries.has(feature.properties.ISO_A3));
const provinces = admin1.features.filter((feature) => feature.properties.adm0_a3 === "CHN");

const points = selected.flatMap((feature) => flatten(feature.geometry.coordinates));
const bounds = points.reduce(
  (value, [lon, lat]) => ({
    minLon: Math.min(value.minLon, lon), maxLon: Math.max(value.maxLon, lon),
    minLat: Math.min(value.minLat, lat), maxLat: Math.max(value.maxLat, lat),
  }),
  { minLon: Infinity, maxLon: -Infinity, minLat: Infinity, maxLat: -Infinity },
);

function flatten(value) {
  if (typeof value[0] === "number") return [value];
  return value.flatMap(flatten);
}

function project([lon, lat]) {
  const drawableWidth = viewBox.width - viewBox.padding * 2;
  const drawableHeight = viewBox.height - viewBox.padding * 2;
  const x = viewBox.padding + ((lon - bounds.minLon) / (bounds.maxLon - bounds.minLon)) * drawableWidth;
  const y = viewBox.padding + ((bounds.maxLat - lat) / (bounds.maxLat - bounds.minLat)) * drawableHeight;
  return [x, y];
}

/** Ramer-Douglas-Peucker on already projected points. */
function simplify(ring, epsilon) {
  if (ring.length < 4) return ring;
  const [first] = ring;
  const last = ring[ring.length - 1];
  let index = 0;
  let maxDistance = 0;
  for (let i = 1; i < ring.length - 1; i += 1) {
    const distance = perpendicular(ring[i], first, last);
    if (distance > maxDistance) { index = i; maxDistance = distance; }
  }
  if (maxDistance <= epsilon) return [first, last];
  return [
    ...simplify(ring.slice(0, index + 1), epsilon).slice(0, -1),
    ...simplify(ring.slice(index), epsilon),
  ];
}

function perpendicular([x, y], [x1, y1], [x2, y2]) {
  const dx = x2 - x1;
  const dy = y2 - y1;
  if (dx === 0 && dy === 0) return Math.hypot(x - x1, y - y1);
  const t = ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy);
  const clamped = Math.max(0, Math.min(1, t));
  return Math.hypot(x - (x1 + clamped * dx), y - (y1 + clamped * dy));
}

function ringArea(ring) {
  let sum = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i, i += 1) {
    sum += (ring[j][0] * ring[i][1]) - (ring[i][0] * ring[j][1]);
  }
  return Math.abs(sum / 2);
}

function ringPath(ring, epsilon) {
  const projected = ring.map(project);
  const reduced = epsilon > 0 ? simplify(projected, epsilon) : projected;
  if (reduced.length < 3) return "";
  return reduced.map(([x, y], index) => `${index === 0 ? "M" : "L"}${x.toFixed(1)} ${y.toFixed(1)}`).join(" ") + " Z";
}

function polygonsOf(geometry) {
  return geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;
}

function geometryPath(geometry, epsilon = 0) {
  return polygonsOf(geometry).flatMap((polygon) => polygon.map((ring) => ringPath(ring, epsilon))).filter(Boolean).join(" ");
}

/** Visual centre of the largest ring, used to anchor province labels. */
function labelPoint(geometry) {
  const rings = polygonsOf(geometry).map((polygon) => polygon[0].map(project));
  const largest = rings.reduce((best, ring) => (ringArea(ring) > ringArea(best) ? ring : best), rings[0]);
  const sum = largest.reduce((value, [x, y]) => [value[0] + x, value[1] + y], [0, 0]);
  return { cx: Number((sum[0] / largest.length).toFixed(1)), cy: Number((sum[1] / largest.length).toFixed(1)) };
}

const outlinePaths = Object.fromEntries(selected.map((feature) => [feature.properties.ISO_A3, geometryPath(feature.geometry)]));

const provincePaths = provinces
  .map((feature) => ({
    id: String(feature.properties.iso_3166_2 || feature.properties.adm1_code).toLowerCase(),
    en: feature.properties.name,
    zh: feature.properties.name_zh ?? feature.properties.name,
    ...labelPoint(feature.geometry),
    d: geometryPath(feature.geometry, EPSILON),
  }))
  .filter((province) => province.d)
  .sort((a, b) => a.id.localeCompare(b.id));

const generated = [
  "// Generated by scripts/build-map.mjs from Natural Earth 1:50m admin-0 countries and",
  "// admin-1 states/provinces (public domain). Do not edit by hand; rerun the script.",
  "",
  `export const MAP_VIEWBOX = { width: ${viewBox.width}, height: ${viewBox.height}, padding: ${viewBox.padding}, bounds: ${JSON.stringify(bounds)} } as const;`,
  "",
  `export const CHINA_OUTLINE_PATHS = ${JSON.stringify(outlinePaths, null, 2)} as const;`,
  "",
  "export type ProvinceShape = { id: string; en: string; zh: string; cx: number; cy: number; d: string };",
  "",
  `export const CHINA_PROVINCE_PATHS: ProvinceShape[] = ${JSON.stringify(provincePaths, null, 2)};`,
  "",
].join("\n");

await writeFile(output, generated);
console.error(`wrote ${output}: ${selected.length} outlines, ${provincePaths.length} provinces, ${(generated.length / 1024).toFixed(0)} KB`);
