import { readFile, writeFile } from "node:fs/promises";

const [input = "/tmp/ne_50m_admin_0_countries.geojson", output = "lib/map-geometry.ts"] = process.argv.slice(2);
const countries = new Set(["CHN", "TWN", "HKG", "MAC"]);
const viewBox = { width: 1000, height: 700, padding: 18 };

const source = JSON.parse(await readFile(input, "utf8"));
const selected = source.features.filter((feature) => countries.has(feature.properties.ISO_A3));

const points = selected.flatMap((feature) => flatten(feature.geometry.coordinates));
const bounds = points.reduce(
  (value, [lon, lat]) => ({
    minLon: Math.min(value.minLon, lon), maxLon: Math.max(value.maxLon, lon),
    minLat: Math.min(value.minLat, lat), maxLat: Math.max(value.maxLat, lat),
  }),
  { minLon: Infinity, maxLon: -Infinity, minLat: Infinity, maxLat: -Infinity },
);

function flatten(value) {
  if (typeof value[0] === "number") return [value];
  return value.flatMap(flatten);
}

function project([lon, lat]) {
  const drawableWidth = viewBox.width - viewBox.padding * 2;
  const drawableHeight = viewBox.height - viewBox.padding * 2;
  const x = viewBox.padding + ((lon - bounds.minLon) / (bounds.maxLon - bounds.minLon)) * drawableWidth;
  const y = viewBox.padding + ((bounds.maxLat - lat) / (bounds.maxLat - bounds.minLat)) * drawableHeight;
  return [x, y];
}

function ringPath(ring) {
  return ring.map((point, index) => {
    const [x, y] = project(point);
    return `${index === 0 ? "M" : "L"}${x.toFixed(1)} ${y.toFixed(1)}`;
  }).join(" ") + " Z";
}

function geometryPath(geometry) {
  const polygons = geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;
  return polygons.flatMap((polygon) => polygon.map(ringPath)).join(" ");
}

const paths = Object.fromEntries(selected.map((feature) => [feature.properties.ISO_A3, geometryPath(feature.geometry)]));
const generated = `// Generated by scripts/build-map.mjs from Natural Earth 1:50m admin-0 countries (public domain).\n// Do not edit by hand; rerun the script with a local GeoJSON input.\n\nexport const MAP_VIEWBOX = { width: ${viewBox.width}, height: ${viewBox.height}, padding: ${viewBox.padding}, bounds: ${JSON.stringify(bounds)} } as const;\n\nexport const CHINA_OUTLINE_PATHS = ${JSON.stringify(paths, null, 2)} as const;\n`;

await writeFile(output, generated);
